---
include:
#  - board: eyelash_corne_left
#    shield: nice_view
#    #snippet: zmk-usb-logging    # Uncomment to log over USB.
  - board: eyelash_corne_left
    shield: nice_view_gem
    artifact-name: gem_left
    snippet: zmk-usb-logging
  - board: eyelash_corne_right
    shield: nice_view_gem
    artifact-name: gem_right
